version: "3.10"
services:
  streamlit_testing:
    build: .
    ports:
      - "8502:8501"
    environment:
      - DISCORD_CLIENT_ID={DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET={DISCORD_CLIENT_SECRET}
      - REDIRECT_URI=http://172.17.0.2:8502
      